CC = gcc
CFLAGS = -Wall -Werror

all: stats

stats: main.o functions.o
	$(CC) $(CFLAGS) -o stats main.o functions.o

main.o: main.c functions.h
	$(CC) $(CFLAGS) -c main.c

functions.o: functions.c functions.h
	$(CC) $(CFLAGS) -c functions.c

clean:
	rm -f *.o stats
